### ISSUE TITLE
is there a way to get it to work over a larger range?

### ISSUE THREAD

**Issue by alexxmarsh44** [greatscottgadgets/plotsweep#6]
it works great for 100 mhz or less spans but i am trying to do a scan from 1:1500 mhz and it simply outputs a blank plot?  is there any way to modify it to work this way?? i know nothing of the rust language or id try im desperate to get a plot over this range.

**Comment by miek** [comment]
It should work OK for wide ranges like that. You may have been running into an issue where a long-running sweep has chunks at plotted at different timestamps, leaving a lot of blank space between them? Recent versions of `hackrf_sweep` have a `-n` flag that keeps the timestamps the same and resolves that.
